// All constants / mock data for the site

import { href } from "react-router-dom"

export const NAV_LINKS = [
  { label: 'Home', href: '#home' },
  { label: 'About', href: '#about' },
  { label: 'Why Choose Us', href: '#why-choose-us' },
  { label: 'Courses', href: '#courses' },
  { label: 'Certificates', href: '#certificate' },
  { label: 'Reviews', href: '#reviews' },
  { label: 'Contact', href: '#contact' },
  { label: 'FAQs', href: 'faq' },
]

export const STATS = [
  { value: 100, suffix: '+', label: 'Hours Training', icon: 'Clock' },
  { value: 5, suffix: '', label: 'Industry Tools', icon: 'Wrench' },
  { value: 7, suffix: '+', label: 'Career Roles', icon: 'Briefcase' },
  { value: 100, suffix: '%', label: 'Job Assistance', icon: 'Trophy' },
]

export const WHY_CARDS = [
  {
    id: 1,
    icon: 'DollarSign',
    title: 'Affordable Fees',
    description: 'World-class education at accessible pricing. Flexible payment plans and EMI options available for all enrolled students.',
    color: 'blue',
    gradient: 'from-blue-50 to-indigo-50',
    iconBg: 'bg-blue-100',
    iconColor: 'text-blue-700',
  },
  {
    id: 2,
    icon: 'Factory',
    title: 'Industry Training',
    description: 'Learn from industry veterans with 10+ years of experience in cloud data analytics and BI engineering.',
    color: 'orange',
    gradient: 'from-orange-50 to-amber-50',
    iconBg: 'bg-orange-100',
    iconColor: 'text-orange-600',
  },
  {
    id: 3,
    icon: 'FolderGit2',
    title: 'Real-Time Projects',
    description: 'Work on live industry datasets and real-world scenarios. Build a portfolio that impresses top recruiters.',
    color: 'emerald',
    gradient: 'from-emerald-50 to-teal-50',
    iconBg: 'bg-emerald-100',
    iconColor: 'text-emerald-700',
  },
  {
    id: 4,
    icon: 'MessagesSquare',
    title: 'Mock Interviews',
    description: 'Comprehensive interview preparation with HR rounds, technical grilling, and expert feedback sessions.',
    color: 'purple',
    gradient: 'from-purple-50 to-violet-50',
    iconBg: 'bg-purple-100',
    iconColor: 'text-purple-700',
  },
  {
    id: 5,
    icon: 'ClipboardCheck',
    title: 'Assessments',
    description: 'Regular evaluations, hands-on assignments, and module-wise assessments to track your progress and mastery.',
    color: 'rose',
    gradient: 'from-rose-50 to-pink-50',
    iconBg: 'bg-rose-100',
    iconColor: 'text-rose-700',
  },
  {
    id: 6,
    icon: 'Trophy',
    title: '100% Job Assistance',
    description: 'Dedicated placement cell, resume building, LinkedIn optimization, and direct referrals to top companies.',
    color: 'blue',
    gradient: 'from-sky-50 to-blue-50',
    iconBg: 'bg-sky-100',
    iconColor: 'text-sky-700',
  },
]

export type CourseCategory = 'All' | 'Excel' | 'SQL' | 'Snowflake' | 'Python' | 'Power BI'

export const COURSES = [
  {
    id: 1,
    slug: 'excel-ai',
    title: 'Microsoft Advanced Excel with AI',
    category: 'Excel' as CourseCategory,
    duration: '25 Hours',
    sessions: '20 Live Sessions',
    mode: 'Online (Live + Recorded)',
    level: 'Beginner to Advanced',
    description: 'Master Excel with AI-powered features, advanced formulas, Power Query, and data visualization for business intelligence.',
    tags: ['Excel', 'Power Query', 'Pivot Tables', 'VBA', 'AI Tools'],
    color: 'from-green-400 to-emerald-600',
    textColor: 'text-green-700',
    bgColor: 'bg-green-50',
    bannerGrad: 'from-green-500 via-emerald-600 to-teal-700',
    syllabus: [
      'Excel Fundamentals & Advanced Formulas (XLOOKUP, LET, LAMBDA)',
      'Power Query for Data Transformation',
      'Advanced Pivot Tables & Pivot Charts',
      'Data Validation & Conditional Formatting',
      'VBA Macros & Automation',
      'AI-powered Excel features (Copilot integration)',
      'Dashboard Design & Data Storytelling',
      'Financial Modeling & Analysis',
    ],
    modules: [
      {
        title: 'Module 1 – Excel Foundations & Advanced Formulas',
        lessons: ['Cell References & Named Ranges', 'XLOOKUP, VLOOKUP, INDEX-MATCH', 'LET & LAMBDA Functions', 'Array Formulas & Dynamic Arrays', 'Date & Text Functions'],
      },
      {
        title: 'Module 2 – Power Query & Data Transformation',
        lessons: ['Power Query Editor Interface', 'Connecting to Multiple Data Sources', 'Data Cleaning & Shaping with M Language', 'Merging & Appending Queries', 'Automating ETL Workflows'],
      },
      {
        title: 'Module 3 – Pivot Tables & Advanced Analysis',
        lessons: ['Creating Complex Pivot Tables', 'Calculated Fields & Items', 'Pivot Charts & Slicers', 'Power Pivot & Data Model', 'DAX Basics in Excel'],
      },
      {
        title: 'Module 4 – VBA & Automation',
        lessons: ['Introduction to VBA & Macros', 'Writing VBA Procedures', 'Loops, Conditions & Error Handling', 'UserForms & Event-Driven Programming', 'Automating Reports'],
      },
      {
        title: 'Module 5 – AI Tools & Dashboard Design',
        lessons: ['Excel Copilot Integration', 'AI-assisted Formula Suggestions', 'Dashboard Design Principles', 'Interactive Charts & Slicers', 'Publishing & Sharing Dashboards'],
      },
    ],
    skills: ['Advanced Excel Formulas', 'Power Query (M Language)', 'Data Cleaning', 'Pivot Analysis', 'VBA Automation', 'Dashboard Design', 'Financial Modeling', 'AI-Assisted Analytics'],
    tools: ['Microsoft Excel 365', 'Power Query', 'Power Pivot', 'VBA Editor', 'Excel Copilot (AI)'],
    projects: [
      { title: 'Sales Performance Dashboard', desc: 'Build a fully interactive sales analytics dashboard with slicers and drill-down capabilities.' },
      { title: 'HR Analytics Report', desc: 'Automate employee data cleaning and generate monthly HR reports using Power Query + VBA.' },
      { title: 'Financial Model', desc: 'Create a 3-statement financial model with dynamic scenarios and sensitivity analysis.' },
    ],
    careers: ['Data Analyst', 'Business Analyst', 'Financial Analyst', 'MIS Executive', 'Operations Analyst', 'Reporting Specialist'],
    faqs: [
      { q: 'Do I need prior Excel knowledge?', a: 'No! We start from the very basics and gradually move to advanced topics. Absolute beginners are welcome.' },
      { q: 'Is this course online or offline?', a: 'This is an online live training program. Recorded sessions are also provided so you never miss a class.' },
      { q: 'Will I get a certificate after completion?', a: 'Yes, upon successful completion of the course and capstone project, you receive an industry-recognized certificate from IntellxSkill Technologies.' },
      { q: 'How long will I have access to the recordings?', a: 'You will have lifetime access to all recorded sessions and course materials.' },
    ],
  },
  {
    id: 2,
    slug: 'sql-server',
    title: 'Microsoft SQL Server',
    category: 'SQL' as CourseCategory,
    duration: '30 Hours',
    sessions: '24 Live Sessions',
    mode: 'Online (Live + Recorded)',
    level: 'Intermediate',
    description: 'Deep dive into SQL Server – T-SQL, stored procedures, performance tuning, and enterprise data management.',
    tags: ['T-SQL', 'Stored Procedures', 'SSMS', 'Performance Tuning', 'SSIS'],
    color: 'from-blue-400 to-blue-700',
    textColor: 'text-blue-700',
    bgColor: 'bg-blue-50',
    bannerGrad: 'from-blue-600 via-blue-700 to-indigo-800',
    syllabus: [
      'T-SQL Fundamentals & Advanced Queries',
      'Database Design & Normalization',
      'Stored Procedures, Functions & Triggers',
      'Indexes & Query Performance Tuning',
      'SQL Server Integration Services (SSIS)',
      'SQL Server Reporting Services (SSRS)',
      'Database Security & Administration',
      'Real-time ETL Pipeline Development',
    ],
    modules: [
      {
        title: 'Module 1 – T-SQL Core Concepts',
        lessons: ['SELECT, WHERE, JOIN, GROUP BY', 'Subqueries & CTEs', 'Window Functions (ROW_NUMBER, RANK, LEAD/LAG)', 'Advanced Aggregations', 'Set Operations (UNION, EXCEPT, INTERSECT)'],
      },
      {
        title: 'Module 2 – Database Design & Normalization',
        lessons: ['Relational Database Concepts', '1NF, 2NF, 3NF, BCNF', 'Primary & Foreign Keys', 'Schema Design for Analytics', 'Star & Snowflake Schemas'],
      },
      {
        title: 'Module 3 – Programmability',
        lessons: ['Stored Procedures & Parameters', 'User-Defined Functions (UDFs)', 'Triggers & Their Use Cases', 'Cursors & Temporary Tables', 'Error Handling with TRY-CATCH'],
      },
      {
        title: 'Module 4 – Performance Tuning',
        lessons: ['Query Execution Plans', 'Clustered & Non-Clustered Indexes', 'Statistics & Query Optimizer', 'Index Fragmentation & Rebuild', 'Query Hints & Optimization'],
      },
      {
        title: 'Module 5 – SSIS, SSRS & Security',
        lessons: ['SSIS Package Development', 'Data Flow & Control Flow', 'SSRS Report Design', 'Row-Level Security', 'SQL Server Agent Jobs'],
      },
    ],
    skills: ['T-SQL Querying', 'Database Design', 'Stored Procedures', 'Performance Tuning', 'ETL Development', 'SSIS/SSRS', 'Database Administration', 'Security Management'],
    tools: ['SQL Server 2022', 'SSMS 20', 'SQL Server Profiler', 'SSIS Designer', 'SSRS Report Builder'],
    projects: [
      { title: 'E-Commerce Data Warehouse', desc: 'Design and populate a star-schema data warehouse from raw e-commerce transaction data.' },
      { title: 'ETL Pipeline with SSIS', desc: 'Build a complete ETL pipeline extracting from Excel/CSV, transforming, and loading into SQL Server.' },
      { title: 'Performance Optimization Challenge', desc: 'Analyze and optimize a set of poorly performing queries using indexes and execution plans.' },
    ],
    careers: ['SQL Developer', 'Database Developer', 'Data Engineer', 'ETL Developer', 'BI Developer', 'Database Administrator'],
    faqs: [
      { q: 'What prior knowledge is required?', a: 'Basic understanding of databases is helpful but not mandatory. We cover all foundational concepts.' },
      { q: 'Which SQL Server version do you teach?', a: 'We primarily use SQL Server 2022 with SSMS 20, the latest versions available.' },
      { q: 'Is SQL Server only for Windows?', a: 'While we teach on Windows environment, SQL Server also runs on Linux and Docker, which we briefly cover.' },
      { q: 'Will this help me crack data engineering interviews?', a: 'Absolutely! We include mock interview questions and scenario-based problems aligned with real interview patterns.' },
    ],
  },
  {
    id: 3,
    slug: 'snowflake',
    title: 'Snowflake Data Warehousing',
    category: 'Snowflake' as CourseCategory,
    duration: '20 Hours',
    sessions: '16 Live Sessions',
    mode: 'Online (Live + Recorded)',
    level: 'Intermediate to Advanced',
    description: 'Become a Snowflake expert – cloud data warehouse architecture, data sharing, performance optimization, and SnowSQL.',
    tags: ['Snowflake', 'Cloud DWH', 'SnowSQL', 'Data Sharing', 'Tasks'],
    color: 'from-cyan-400 to-sky-600',
    textColor: 'text-sky-700',
    bgColor: 'bg-sky-50',
    bannerGrad: 'from-cyan-500 via-sky-600 to-blue-700',
    syllabus: [
      'Snowflake Architecture & Concepts',
      'Virtual Warehouses & Resource Monitors',
      'Data Loading & Unloading (Stages, COPY INTO)',
      'Semi-structured Data (JSON, Parquet, Avro)',
      'Snowflake Tasks, Streams & Pipes',
      'Role-Based Access Control & Security',
      'Snowflake Data Sharing & Marketplace',
      'Performance Optimization & Cost Management',
    ],
    modules: [
      {
        title: 'Module 1 – Snowflake Architecture',
        lessons: ['Multi-cluster Shared Data Architecture', 'Storage, Compute & Cloud Services Layers', 'Virtual Warehouses & Scaling', 'Micro-partitioning & Clustering', 'Snowflake Editions & Pricing'],
      },
      {
        title: 'Module 2 – Data Loading & Stages',
        lessons: ['Internal & External Stages', 'COPY INTO Command', 'Snowpipe for Continuous Loading', 'File Format Objects', 'Loading JSON & Parquet Data'],
      },
      {
        title: 'Module 3 – Snowflake SQL & Semi-structured Data',
        lessons: ['Snowflake SQL Dialect', 'VARIANT Data Type & FLATTEN', 'Querying JSON with Dot Notation', 'PARSE_JSON & TO_JSON', 'Array & Object Functions'],
      },
      {
        title: 'Module 4 – Tasks, Streams & Data Pipelines',
        lessons: ['Snowflake Streams for CDC', 'Tasks for Scheduling', 'Building ELT Pipelines', 'Dynamic Tables', 'Snowpark for Python'],
      },
      {
        title: 'Module 5 – Security, Sharing & Cost Optimization',
        lessons: ['RBAC & Privilege Management', 'Data Masking Policies', 'Row-Level Access Policies', 'Data Sharing & Marketplace', 'Query Performance & Cost Control'],
      },
    ],
    skills: ['Snowflake SQL', 'Cloud Data Warehouse Design', 'Data Loading & Pipelines', 'Semi-structured Data Processing', 'Performance Optimization', 'Security & Governance', 'Data Sharing', 'Snowpark'],
    tools: ['Snowflake (Trial Account)', 'SnowSQL CLI', 'Snowflake Web UI', 'VS Code + Snowflake Extension', 'dbt (intro)'],
    projects: [
      { title: 'Cloud Data Warehouse Build', desc: 'Design and implement a cloud data warehouse from scratch using Snowflake with proper RBAC and staging.' },
      { title: 'Real-Time Streaming Pipeline', desc: 'Build a CDC pipeline using Snowflake Streams and Tasks to process real-time transactional data.' },
      { title: 'JSON Analytics Platform', desc: 'Ingest, parse, and analyze nested JSON clickstream data using Snowflake VARIANT and FLATTEN.' },
    ],
    careers: ['Snowflake Developer', 'Cloud Data Engineer', 'Data Warehouse Architect', 'Analytics Engineer', 'Platform Engineer', 'Data Platform Lead'],
    faqs: [
      { q: 'Do I need a paid Snowflake account?', a: 'No. Snowflake offers a free 30-day trial with $400 credits — more than enough for the entire course.' },
      { q: 'Is Snowflake only used in large companies?', a: 'Not at all! Snowflake is used by startups to Fortune 500s. Its pay-per-use model makes it accessible for teams of all sizes.' },
      { q: 'Will I learn dbt in this course?', a: 'We provide an introduction to dbt (data build tool) as an analytics engineering layer on top of Snowflake.' },
      { q: 'Is Snowflake certification covered?', a: 'This course prepares you for the SnowPro Core Certification. We cover all exam topics and provide practice questions.' },
    ],
  },
  {
    id: 4,
    slug: 'python-data-analytics',
    title: 'Python for Data Analytics',
    category: 'Python' as CourseCategory,
    duration: '35 Hours',
    sessions: '28 Live Sessions',
    mode: 'Online (Live + Recorded)',
    level: 'Beginner to Advanced',
    description: 'Master Python for data science – Pandas, NumPy, Matplotlib, Seaborn, and Scikit-learn for predictive analytics.',
    tags: ['Python', 'Pandas', 'NumPy', 'Matplotlib', 'Scikit-learn'],
    color: 'from-yellow-400 to-orange-500',
    textColor: 'text-orange-700',
    bgColor: 'bg-orange-50',
    bannerGrad: 'from-yellow-500 via-orange-500 to-red-600',
    syllabus: [
      'Python Fundamentals & OOP Concepts',
      'NumPy for Numerical Computing',
      'Pandas for Data Manipulation & Analysis',
      'Data Cleaning & Preprocessing',
      'Exploratory Data Analysis (EDA)',
      'Matplotlib & Seaborn for Visualization',
      'Statistical Analysis & Hypothesis Testing',
      'Introduction to ML with Scikit-learn',
    ],
    modules: [
      {
        title: 'Module 1 – Python Foundations',
        lessons: ['Python Syntax & Data Types', 'Lists, Tuples, Dicts & Sets', 'Functions, Lambdas & Closures', 'OOP: Classes, Inheritance & Polymorphism', 'File I/O & Exception Handling'],
      },
      {
        title: 'Module 2 – NumPy & Scientific Computing',
        lessons: ['ndarray & Broadcasting', 'Array Operations & Math Functions', 'Linear Algebra with NumPy', 'Random Number Generation', 'Performance vs Python Lists'],
      },
      {
        title: 'Module 3 – Pandas Data Analysis',
        lessons: ['Series & DataFrame Operations', 'Data Cleaning (Missing Values, Duplicates)', 'Merging, Joining & Reshaping', 'GroupBy & Aggregations', 'Time Series Analysis'],
      },
      {
        title: 'Module 4 – Data Visualization',
        lessons: ['Matplotlib Figures & Axes', 'Line, Bar, Scatter, Histogram Plots', 'Seaborn Statistical Visualizations', 'Heatmaps & Correlation Matrices', 'Plotly for Interactive Dashboards'],
      },
      {
        title: 'Module 5 – Statistics & Machine Learning Intro',
        lessons: ['Descriptive & Inferential Statistics', 'Hypothesis Testing (t-test, Chi-square)', 'Correlation & Regression Analysis', 'Scikit-learn Pipeline', 'Linear & Logistic Regression'],
      },
    ],
    skills: ['Python Programming', 'NumPy & Pandas', 'Data Cleaning', 'Exploratory Data Analysis', 'Data Visualization', 'Statistical Analysis', 'Machine Learning Basics', 'Jupyter Notebooks'],
    tools: ['Python 3.12', 'Jupyter Notebook / JupyterLab', 'Pandas', 'NumPy', 'Matplotlib', 'Seaborn', 'Plotly', 'Scikit-learn'],
    projects: [
      { title: 'Customer Churn Analysis', desc: 'Perform full EDA on a telecom dataset to identify churn patterns and build a predictive model.' },
      { title: 'E-Commerce Sales Dashboard', desc: 'Clean, analyse and visualize 1M+ rows of e-commerce data with Plotly interactive charts.' },
      { title: 'Stock Market Analysis', desc: 'Analyze historical stock prices, compute moving averages and visualize trends with Matplotlib.' },
    ],
    careers: ['Data Analyst', 'Python Developer', 'Data Scientist (Junior)', 'Business Intelligence Analyst', 'Machine Learning Engineer', 'Research Analyst'],
    faqs: [
      { q: 'Do I need programming experience to join?', a: 'No prior programming experience is needed. We start from the absolute basics of Python.' },
      { q: 'Will this course help me become a Data Scientist?', a: 'This course provides a strong foundation for data science. It covers the core analytics skills and introduces machine learning concepts.' },
      { q: 'What IDE or environment will we use?', a: 'We primarily use Jupyter Notebook and VS Code. Setup guides are provided for all platforms.' },
      { q: 'Is Python enough for a data job?', a: 'Python combined with SQL and visualization tools (Power BI) is a highly in-demand combination. We recommend pairing this with our SQL or Power BI course.' },
    ],
  },
  {
    id: 5,
    slug: 'power-bi',
    title: 'Microsoft Power BI',
    category: 'Power BI' as CourseCategory,
    duration: '30 Hours',
    sessions: '24 Live Sessions',
    mode: 'Online (Live + Recorded)',
    level: 'Beginner to Advanced',
    description: 'Build stunning Power BI dashboards – DAX mastery, data modeling, Power Query, and enterprise reporting.',
    tags: ['Power BI', 'DAX', 'Power Query', 'Data Model', 'Reports'],
    color: 'from-yellow-500 to-amber-600',
    textColor: 'text-amber-700',
    bgColor: 'bg-amber-50',
    bannerGrad: 'from-yellow-500 via-amber-500 to-orange-600',
    syllabus: [
      'Power BI Desktop & Service Overview',
      'Data Sources, Connections & Power Query M',
      'Data Modeling (Star Schema, Relationships)',
      'DAX Fundamentals & Advanced Calculations',
      'Time Intelligence Functions',
      'Interactive Reports & Dashboard Design',
      'Row-Level Security (RLS)',
      'Power BI Service, Workspaces & Deployment',
    ],
    modules: [
      {
        title: 'Module 1 – Power BI Fundamentals',
        lessons: ['Power BI Desktop Interface', 'Connecting to Data Sources', 'Power Query Editor Basics', 'Loading & Refreshing Data', 'Publishing to Power BI Service'],
      },
      {
        title: 'Module 2 – Power Query & Data Transformation',
        lessons: ['M Language Fundamentals', 'Data Cleaning & Shaping', 'Merging & Appending Queries', 'Custom Columns & Functions', 'Incremental Refresh Setup'],
      },
      {
        title: 'Module 3 – Data Modeling',
        lessons: ['Star Schema & Snowflake Schema', 'Relationships & Cardinality', 'Calculated Columns vs Measures', 'Hidden Fields & Display Folders', 'Composite Models'],
      },
      {
        title: 'Module 4 – DAX Mastery',
        lessons: ['DAX Syntax & Context', 'CALCULATE & FILTER Functions', 'Time Intelligence (YTD, QTD, MoM)', 'RANKX, TOPN & Advanced Measures', 'Variables in DAX'],
      },
      {
        title: 'Module 5 – Reporting, Security & Deployment',
        lessons: ['Visual Best Practices', 'Bookmarks, Drill-through & Tooltips', 'Row-Level Security (RLS)', 'Power BI Service Workspaces', 'Dataflows, Apps & Governance'],
      },
    ],
    skills: ['Power BI Desktop & Service', 'Power Query (M Language)', 'DAX Calculations', 'Data Modeling', 'Dashboard Design', 'Time Intelligence', 'Row-Level Security', 'Report Publishing'],
    tools: ['Power BI Desktop', 'Power BI Service', 'DAX Studio', 'Tabular Editor', 'Power Query Editor'],
    projects: [
      { title: 'Executive Sales Dashboard', desc: 'Build a C-suite ready sales dashboard with YTD comparisons, regional drill-downs, and KPI cards.' },
      { title: 'HR Analytics Report', desc: 'Create an HR metrics dashboard with headcount trends, attrition analysis, and RLS by department.' },
      { title: 'Financial P&L Report', desc: 'Design a Profit & Loss statement report with dynamic time intelligence and variance analysis.' },
    ],
    careers: ['Power BI Developer', 'BI Analyst', 'Data Analyst', 'Reporting Analyst', 'Business Intelligence Engineer', 'Analytics Consultant'],
    faqs: [
      { q: 'Is Power BI Desktop free?', a: 'Yes! Power BI Desktop is completely free to download. Power BI Service has a free tier and paid Pro/Premium licenses.' },
      { q: 'How hard is DAX to learn?', a: 'DAX has a learning curve but our structured approach makes it very approachable. We start from basics and build complexity gradually.' },
      { q: 'Will I learn Power BI for both Desktop and Cloud?', a: 'Absolutely! We cover both Power BI Desktop (reporting tool) and Power BI Service (cloud publishing, sharing, governance).' },
      { q: 'Is Power BI certification covered?', a: 'This course aligns with the PL-300 (Microsoft Power BI Data Analyst) certification exam objectives.' },
    ],
  },
]

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Priya Sharma',
    role: 'Data Analyst',
    company: 'Infosys',
    review: 'The Cloud Data Analytics program completely transformed my career. The hands-on projects and mock interviews gave me the confidence to crack interviews at top MNCs. Highly recommend IntellxSkill!',
    rating: 5,
    avatar: 'PS',
    avatarColor: 'from-blue-400 to-indigo-600',
  },
  {
    id: 2,
    name: 'Rahul Mehta',
    role: 'BI Engineer',
    company: 'Wipro',
    review: 'Exceptional training quality! The Power BI and Snowflake modules were incredibly detailed. Got placed within 3 weeks of completing the course. The placement cell is truly amazing.',
    rating: 5,
    avatar: 'RM',
    avatarColor: 'from-orange-400 to-rose-500',
  },
  {
    id: 3,
    name: 'Sneha Patel',
    role: 'SQL Developer',
    company: 'TCS',
    review: 'From a complete beginner to a SQL expert – IntellxSkill made it possible. The instructor explanations are crystal clear, and the real-time projects made all the difference.',
    rating: 5,
    avatar: 'SP',
    avatarColor: 'from-emerald-400 to-teal-600',
  },
  {
    id: 4,
    name: 'Arjun Nair',
    role: 'Data Engineer',
    company: 'Accenture',
    review: 'The curriculum is perfectly aligned with industry requirements. Python for Data Analytics was especially well-structured. IntellxSkill is the best investment I made for my career.',
    rating: 5,
    avatar: 'AN',
    avatarColor: 'from-purple-400 to-violet-600',
  },
  {
    id: 5,
    name: 'Kavitha Reddy',
    role: 'Analytics Consultant',
    company: 'Deloitte',
    review: 'The mentors here are phenomenal! They go above and beyond to help students understand concepts. The certificate from IntellxSkill carries real value in the job market.',
    rating: 5,
    avatar: 'KR',
    avatarColor: 'from-rose-400 to-pink-600',
  },
  {
    id: 6,
    name: 'Vikram Singh',
    role: 'Power BI Developer',
    company: 'HCL Technologies',
    review: 'IntellxSkill provides world-class education at affordable prices. The Excel with AI module was mind-blowing. I now build enterprise dashboards for Fortune 500 clients!',
    rating: 5,
    avatar: 'VS',
    avatarColor: 'from-sky-400 to-blue-600',
  },
]

export const CONTACT_INFO = {
  address: '3rd Floor, Tech Hub, Andheri East, Mumbai - 400069, Maharashtra',
  phone: '+91 98765 43210',
  email: 'hello@intellxskill.com',
  website: 'www.intellxskill.com',
  hours: 'Mon–Sat: 9:00 AM – 7:00 PM',
}

export const COURSE_OPTIONS = [
  'Microsoft Advanced Excel with AI',
  'Microsoft SQL Server',
  'Snowflake Data Warehousing',
  'Python for Data Analytics',
  'Microsoft Power BI',
  'Full Program Bundle',
]

export const SOCIAL_LINKS = [
  { icon: 'Linkedin', label: 'LinkedIn', href: '#' },
  { icon: 'Youtube', label: 'YouTube', href: '#' },
  { icon: 'Instagram', label: 'Instagram', href: '#' },
  { icon: 'Twitter', label: 'Twitter', href: '#' },
]

export const ABOUT_TABS = [
  {
    id: 'approach',
    label: 'Our Approach',
    icon: 'Lightbulb',
    title: 'Learn by Doing, Not Just Watching',
    description: 'Our curriculum is built around practical application. Every concept is reinforced with hands-on labs, real datasets, and live projects that mirror actual industry workflows.',
    points: [
      'Live instructor-led sessions with Q&A',
      'Hands-on labs with real industry datasets',
      'Weekly capstone projects',
      'Industry mentorship & guidance',
    ],
  },
  {
    id: 'assessments',
    label: 'Assessments',
    icon: 'ClipboardCheck',
    title: 'Track Your Mastery at Every Step',
    description: 'We use a multi-tiered assessment system to ensure every student achieves mastery before moving forward, building confidence progressively.',
    points: [
      'Module-end quizzes & practical tests',
      'Weekly assignments & submissions',
      'Mid-program comprehensive review',
      'Final capstone project evaluation',
    ],
  },
  {
    id: 'career',
    label: 'Career Support',
    icon: 'Briefcase',
    title: 'We Don\'t Stop Until You\'re Hired',
    description: 'Our dedicated career services team works with you from day one to ensure you land your dream role in data analytics or BI engineering.',
    points: [
      'Resume & LinkedIn profile optimization',
      'Mock interviews with industry experts',
      'Direct placement referrals to 150+ companies',
      'Lifetime career support membership',
    ],
  },
]

export const FILTER_CATEGORIES: CourseCategory[] = ['All', 'Excel', 'SQL', 'Snowflake', 'Python', 'Power BI']
